### ISSUE TITLE
Mob attack speed and range seem weird?

### ISSUE THREAD

**Issue by polykatt** [Thelnfamous1/Better-Mob-Combat#13]
I'm not sure but mobs seem to be spamming attacks. Maybe I'm wrong but is this mod possibly changing regular attack speed for mobs? Also they seem to have more range as well. Maybe this can be fixed?

Edit: Oh, never mind I just saw the attack speed modifier in the config. So changing that value of 7 will change the attack cooldown?

**Comment by Thelnfamous1** [comment]
Mobs have a 7-tick delay by default in between Better Combat attacks. Their attack range becomes identical to the weapon with Better Combat attributes that they are holding.

As the config says, the value of 7 was picked since standard Better Combat sword attacks take about 13 ticks, and in vanilla, mobs have a standard delay of 20 ticks between attacks. 13+7=20. But of course, you are free to adjust this to your preferences.

**Comment by polykatt** [comment]
I see, that makes total sense. I'm wondering though if it's possible to match the attack cooldowns to the better combat weapon that they're holding? So then instead of the standard 20 tick delay for mobs they'd actually have delay that matches the player with whatever the weapon attributes may be

**Comment by Thelnfamous1** [comment]
With the default mob attack delay value, they already attack slower than players. Players can chain attacks very quickly using Better Combat.

I can consider adding a way to fine tune mob attack cooldown on a per-weapon basis. But that would be part of a larger update that changes the mod's system to have files per mob instead of using what's been loaded for players.
