### ISSUE TITLE
Mob accidentally attacked Mob

### ISSUE THREAD

**Issue by INV-PLA** [Thelnfamous1/Better-Mob-Combat#3]
For example, when a Zombified Piglin attacks a player and tries to attack them, it may harm its own kind and lead to mutual attacks. I am not sure if this was intentional or accidental, but I will treat it as erroneous feedback. If my feedback is intentional design, please let me know

**Comment by Thelnfamous1** [comment]
This is technically intended design, since the only thing that the custom attacks check are whether or not any hit mobs are allied to the attacker. For example, Illagers will not accidentally hit each other with the custom attacks, since they are considered part of the same team. 

I can introduce a config option similar to the one Better Combat provides for players to fine-tune relations on a per-mob basis.

**Comment by Thelnfamous1** [comment]
Fixed by 6b5b9e5. Be on the lookout for Better Mob Combat 1.1.2 which comes with brand new config options, and preset values for zombified piglins to not attack each other accidentally.
